version: '3'
tasks:
  api:dev:
    desc: Start the API in development mode (with live reloading)
    deps:
      - api:dev:build
      - api:migrate
  api:dev:build:
    desc: Build the Go binary
    dir: "./api"
    cmd: air -c .air.toml
  api:migrate:
    desc: Migrate up to the latest version
    dir: "./api/migrations"
    cmd: "tern migrate"