package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"net/http"
	"setlist/auth"
	"setlist/graph"
	"time"

	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*graph.Session, error) {
	res, err := r.auth.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}

	rw, ok := graph.ResponseWriter(ctx)
	if !ok {
		r.logger.Error("could not fetch response writer ctx key")
		return nil, fmt.Errorf("internal server error")
	}

	ttl := auth.RefreshTokenTTL
	c := &http.Cookie{
		Name:     "setlist-refresh-token",
		Value:    res.RefreshToken,
		HttpOnly: true,
		Secure:   r.env.IsProduction(),
		SameSite: http.SameSiteLaxMode,
		Path:     "/graphql",
		Expires:  time.Now().Add(ttl),
		MaxAge:   int(ttl.Seconds()),
	}

	http.SetCookie(rw, c)

	s := &graph.Session{
		UserID:      res.UserID,
		AccessToken: res.AccessToken,
	}

	return s, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, userID uuid.UUID) (*graph.Session, error) {
	panic(fmt.Errorf("not implemented: Session - session"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
