FROM golang:1.26.1-alpine

WORKDIR /app/api

# Copy the source from the current directory to the workspace
ADD . .

# Pre-download dependencies and only redownload them in subsequent builds if they change
COPY /api/go.mod /api/go.sum ./
RUN go mod download && go mod verify

# Install Task for running various tasks
RUN go install github.com/go-task/task/v3/cmd/task@v3.49.1
# Install Air for live reloading
RUN go install github.com/air-verse/air@v1.64.5
# Install gqlgen for GraphQL generation
RUN go install github.com/99designs/gqlgen@v0.17.88
# Install tern for migrations
RUN go install github.com/jackc/tern/v2@v2.3.5
