// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/google/uuid"
)

type Mutation struct {
}

type NewUser struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Email     string  `json:"email"`
}

type Query struct {
}

type Session struct {
	UserID      uuid.UUID `json:"userID"`
	AccessToken string    `json:"accessToken"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	FirstName *string   `json:"firstName,omitempty"`
	LastName  *string   `json:"lastName,omitempty"`
	Email     string    `json:"email"`
}
